services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: fitness_booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: gunicorn fitness_booking.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # Share static files with NGINX
    depends_on:
      - db
    environment:
      - POSTGRES_DB=fitness_booking_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - DB_HOST=db
      - DB_PORT=5432

  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/app/staticfiles  # Share static volume
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume:
