version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fitness_network  # No external: true

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://user:password@db/dbname  # Django will use this to connect
    ports:
      - "8000:8000"
    networks:
      - fitness_network  # No external: true

volumes:
  postgres_data:

networks:
  fitness_network:
    driver: bridge  # Define the network driver for internal networking
