version: "3.8"

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: fitness_booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password  # Replace with your actual password
    ports:
      - "5432:5432"  # Remove the duplicate line
    volumes:
      - postgres_data:/var/lib/postgresql/data  # Remove the duplicate line
    networks:
      - fitness_network

  web:
    build: .
    container_name: fitness_web
    ports:
      - "8000:8000"
    networks:
      - fitness_network
    depends_on:
      - db

volumes:
  postgres_data:

networks:
  fitness_network:
    driver: bridge
