version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
      - ./static:/app/static  # Volume for static files
      - ./media:/app/media    # Volume for media files
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - default

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fitness_booking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
    external:
      name: fitness_network  # Optional, if you want to customize network name

