version: '3'

services:
  web:
    build:
      context: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fitness_booking_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
