version: "3.9"

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fitness_booking
    ports:
      - "5432:5432"

  web:
    build:
      context: .  # This will use the current directory (root) as the build context
      dockerfile: Dockerfile  # This ensures the correct Dockerfile is used
    command: bash -c "wait-for-it db:5432 -- python manage.py migrate && gunicorn fitness_booking.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

