services:
  db:
    image: postgres:latest
    container_name: fitness_db
    environment:
      POSTGRES_DB: fitness_booking_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password  # Use a secure password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - fitness_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d fitness_booking_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: fitness_web
    ports:
      - "8000:8000"
    networks:
      - fitness_network
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql://postgres:password@db:5432/fitness_booking_db"
    volumes:
      - .:/app

volumes:
  postgres_data:

networks:
  fitness_network:
    driver: bridge

