# Generated by Django 4.2.20 on 2025-03-24 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("booking", "0002_booking_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="class",
            name="description",
        ),
        migrations.RemoveField(
            model_name="trainer",
            name="bio",
        ),
        migrations.AlterField(
            model_name="booking",
            name="user_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="booking",
            name="user_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="class",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
