name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: fitness_db
        ports:
          - "5432:5432"
        options: >-
          --health-cmd "pg_isready -U postgres"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Linting
        run: |
          pip install flake8
          flake8 fitness_booking

      - name: Run Tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/fitness_db
        run: |
          python manage.py test

      - name: Build Docker Image
        run: |
          docker build -t fitness-booking:latest .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Push Docker Image
        run: |
          docker tag fitness-booking:latest ${{ secrets.DOCKER_HUB_USERNAME }}/fitness-booking:latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/fitness-booking:latest

